name: Publish Docker Image
run-name: Publishing Pushed Items of ${{ github.actor }}

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed

jobs:
  docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Collecting information from version file
        run: bash .github/scripts/getversion.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to docker Hub
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building & Publishing images
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6
          push: true
          tags: ghcr.io/biltudas1/crawler-db:${{ env.Version }}-${{ env.VersionType }},ghcr.io/biltudas1/crawler-db:latest
